apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sre-app-alerts
  namespace: default
  labels:
    release: monitoring
spec:
  groups:
    - name: sre-app.rules
      rules:
        - alert: HighErrorRate
          expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Taux d'erreur élevé sur sre-app"
            description: "Le taux de requêtes en erreur 5xx dépasse 0.1 req/s depuis 2 minutes sur {{ $labels.instance }}."