replicaCount: 3

nameOverride: ""
fullnameOverride: ""

image:
  repository: sre-app
  tag: v2
  pullPolicy: Never

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8000

autoscaling:
  enabled: false

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

httpRoute:
  enabled: false
  hostnames: []
  parentRefs: []
  rules: []

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "250m"
    memory: "128Mi"

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 3

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

nodeSelector: {}
tolerations: []
affinity: {}

volumes: []
volumeMounts: []